package com.eternalxi.eternalxi_api.dto.rewards;

/**
 * Respuesta unificada de canje; solo aplican campos según {@code tipoEfecto}.
 */
public record LeagueCardRedeemResponse(
        boolean cartaUsada,
        String tipoEfecto,
        Long idLigaJugador,
        String nombreJugador,
        Long valorBase,
        Double multiplicadorVenta,
        Long cantidadRecibida,
        Long nuevoDineroLiga,
        Long idUsuarioPropietarioAnterior,
        String nicknamePropietarioAnterior,
        Long idUsuarioNuevoPropietario,
        String nicknameNuevoPropietario,
        /** Valor de mercado en BD (base) usado en cláusula. */
        Long valorJugadorClausula,
        Long pagadoPorAtacante,
        Long recibidoPorPropietario,
        Long nuevoDineroAtacante,
        Long nuevoDineroPropietario,
        Long idJornadaInicioProteccion,
        Long idJornadaFinProteccion,
        Boolean proteccionHastaFinTemporada,
        Integer puntosAnadidos,
        Integer totalBonusAcumulado,
        Integer puntosFantasyLiga,
        Integer puntosTotalesEfectivos,
        Long valorAnterior,
        Double porcentajeRecuperacion,
        Long valorTemporal,
        Long idJornadaExpiracion,
        Long valorMercadoEfectivo,
        Double porcentajeModificadorValorActivo
) {
    public static LeagueCardRedeemResponse sell(
            long idLj,
            String nombre,
            long valorBase,
            long valorMercadoEfectivo,
            Double porcentajeModificadorValorActivo,
            double mult,
            long recibido,
            long nuevoDinero
    ) {
        return new LeagueCardRedeemResponse(
                true,
                CardEffectType.SELL_PLAYER_BONUS.name(),
                idLj,
                nombre,
                valorBase,
                mult,
                recibido,
                nuevoDinero,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                valorMercadoEfectivo,
                porcentajeModificadorValorActivo
        );
    }

    public static LeagueCardRedeemResponse clause(
            long idLj,
            String nombre,
            long prevOwner,
            String nickPrev,
            long newOwner,
            String nickNew,
            long valorBaseMercado,
            long valorMercadoEfectivo,
            Double porcentajeModificadorValorActivo,
            long paid,
            long received,
            long moneyAtt,
            long moneyOwner
    ) {
        return new LeagueCardRedeemResponse(
                true,
                CardEffectType.DIRECT_CLAUSE.name(),
                idLj,
                nombre,
                null,
                null,
                null,
                null,
                prevOwner,
                nickPrev,
                newOwner,
                nickNew,
                valorBaseMercado,
                paid,
                received,
                moneyAtt,
                moneyOwner,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                valorMercadoEfectivo,
                porcentajeModificadorValorActivo
        );
    }

    public static LeagueCardRedeemResponse protect(
            long idLj,
            String nombre,
            Long jIni,
            Long jFin,
            boolean season
    ) {
        return new LeagueCardRedeemResponse(
                true,
                CardEffectType.PROTECT_PLAYER.name(),
                idLj,
                nombre,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                jIni,
                jFin,
                season,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public static LeagueCardRedeemResponse leaguePoints(
            int added,
            int totalBonus,
            int fantasy,
            int efectivos
    ) {
        return new LeagueCardRedeemResponse(
                true,
                CardEffectType.ADD_LEAGUE_POINTS.name(),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                added,
                totalBonus,
                fantasy,
                efectivos,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }

    public static LeagueCardRedeemResponse valueBoost(
            long idLj,
            String nombre,
            long valorAnterior,
            long valorNuevo,
            double pct,
            double valoracionNueva
    ) {
        return new LeagueCardRedeemResponse(
                true,
                CardEffectType.PLAYER_VALUE_BOOST.name(),
                idLj,
                nombre,
                valorAnterior,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                valorAnterior,
                pct,
                valorNuevo,
                null,
                valorNuevo,
                null
        );
    }

    @Deprecated
    public static LeagueCardRedeemResponse valueRecovery(
            long idLj,
            String nombre,
            long valor,
            long valorAnt,
            double pct,
            long valorTemp,
            Long idJornadaExp,
            long valorMercadoEfectivo,
            Double porcentajeModificadorValorActivo
    ) {
        return new LeagueCardRedeemResponse(
                true,
                CardEffectType.PLAYER_VALUE_BOOST.name(),
                idLj,
                nombre,
                valor,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                valorAnt,
                pct,
                valorTemp,
                idJornadaExp,
                valorMercadoEfectivo,
                porcentajeModificadorValorActivo
        );
    }
}
